// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Api.Data;

#nullable disable

namespace RecipeShare.Api.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20251001195016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("DietaryTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTimeMinutes = 20,
                            DietaryTags = "vegetarian",
                            Ingredients = "pasta, tomato sauce, garlic, olive oil, salt",
                            Steps = "Boil pasta. Heat sauce. Combine and serve.",
                            Title = "Simple Tomato Pasta"
                        },
                        new
                        {
                            Id = 2,
                            CookingTimeMinutes = 10,
                            DietaryTags = "vegetarian,gluten-free",
                            Ingredients = "cucumber, tomato, red onion, feta, olive oil, lemon",
                            Steps = "Chop ingredients, toss with dressing.",
                            Title = "Greek Salad"
                        },
                        new
                        {
                            Id = 3,
                            CookingTimeMinutes = 5,
                            DietaryTags = "vegetarian",
                            Ingredients = "bread, avocado, lemon, salt, pepper",
                            Steps = "Toast bread, mash avocado, season, spread on toast.",
                            Title = "Avocado Toast"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
